/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//In this class we can enter new student
package studentmanagementsystem;

import Information.*;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

// THIS CLASS ADDS NEW STUDENT IN LIST

/**
 *
 * @author USER
 */
public class EditInfo extends javax.swing.JFrame {

    /**
     * Creates new form EditInfo
     */
    StudentLogin sl=new StudentLogin();
    DashBoard db=new DashBoard();
    public EditInfo() {
        initComponents();
        DeptField.setText(StudentLogin.dept);
    }
    Connection con;
    PreparedStatement pst,pst2,pst3,pst4,pst5;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NameField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FathersNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MotherNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DeptField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AgeField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BDateField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BloodGroupField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        GenderField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        YearField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        SemesterField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        emailFeild = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ContactField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        GNUM = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        AddressField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CGPA = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(26, 204, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Add New Student");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(181, 231, 146));

        SaveButton.setBackground(new java.awt.Color(232, 242, 225));
        SaveButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(232, 242, 225));
        CancelButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
            .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Name                 :");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Fathers Name   :");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Mothers Name  :");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Department       :");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Age     :");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("ID   :");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Birth Date :");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Blood Group :");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Gender:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Class                :");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Section:");

        SemesterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemesterFieldActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("E-mail                :");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Contact No       :");

        ContactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactFieldActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Gurdian Conact No:");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Address            :");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("CGPA :");
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(71, 71, 71)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NameField1)
                                .addComponent(FathersNameField)
                                .addComponent(DeptField, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                                .addComponent(MotherNameField))
                            .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GNUM, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(SemesterField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(176, 176, 176)
                                                .addComponent(CGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BloodGroupField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(GenderField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(YearField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailFeild)
                                .addComponent(ContactField, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                            .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FathersNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MotherNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeptField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BDateField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BloodGroupField))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(GenderField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(IDField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YearField, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SemesterField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emailFeild)
                                .addGap(2, 2, 2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(GNUM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ContactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactFieldActionPerformed

    private void SemesterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemesterFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SemesterFieldActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        StudentInfo st=new StudentInfo();
        st.setID(Integer.parseInt(IDField.getText()));
        st.setName(NameField1.getText());
        st.setFatherName(FathersNameField.getText());
        st.setMotherName(MotherNameField.getText());
        st.setDept(DeptField.getText());
        int age=Integer.parseInt(AgeField.getText());
        st.setBirthDate(BDateField.getText());
        st.setbloodgroup(BloodGroupField.getText());
        st.setgender(GenderField.getText());
        st.setClass(Integer.parseInt(YearField.getText()));
        st.setSemester(Integer.parseInt(SemesterField.getText()));
        st.setEmail(emailFeild.getText());
        st.setmobileNo(Integer.parseInt(ContactField.getText()));
        st.setphone(Integer.parseInt(GNUM.getText()));
        st.setAddress(AddressField.getText());
        st.setCGPA(CGPA.getText());
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/studentmanagement","root","");
            pst=(PreparedStatement) con.prepareStatement("insert into userinfo(id,name,FatherName,MotherName,Dept,Age,BirthDate,BloodGroup,Gender,Class,Semester,Email,ContactNo,GurdianContact,Address,CGPA)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst5=(PreparedStatement) con.prepareStatement("INSERT INTO parfoemance(id, Name, Dept, Class, Section, TotalWorkDays, Present, Absent, Behavior) VALUES (?,?,?,?,?,?,?,?,?)");
            
            pst5.setInt(1, st.getID());
            pst5.setString(2, st.getName());
            pst5.setString(3, st.getDept());
            pst5.setInt(4, st.getclass());
            pst5.setString(5, Integer.toString(st.getSemester()));
            pst5.setInt(6, 125);
            pst5.setInt(7, 0);
            pst5.setInt(8, 0);
            pst5.setString(9, "Good");
            
            if("Science".equals(st.getDept()))
            {
                pst2=(PreparedStatement) con.prepareStatement("INSERT INTO sciencesubjects(id, Name, Semester, Class, Bangla1st, B1CQ, B1MCQ, Bangla2nd, B2CQ, B2MCQ, English1st, English2nd, HigherMath1st, HM1CQ, HM1MCQ, HM1Lab, HigherMath2nd, HM2CQ, HM2MCQ, HM2Lab, Physics1st, PHY1CQ, PHY1MCQ, PHY1Lab, Physics2nd, PHY2CQ, PHY2MCQ, PHY2Lab, Chemistry1st, CHE1CQ, CHE1MCQ, CHE1Lab, Chemistry2nd, CHE2CQ, CHE2MCQ, CHE2Lab, Biology1st, BIO1CQ, BIO1MCQ, BIO1Lab, Biology2nd, BIO2CQ, BIO2MCQ, BIO2Lab, ICT, ICTCQ, ICTMCQ, ICTLab, TotalMarks) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                System.out.println("here i am.workin");
                
                pst2.setInt(1, st.getID());
                pst2.setString(2, st.getName());
                pst2.setInt(3, st.getSemester());
                pst2.setInt(4, st.getclass());
                pst2.setDouble(5, 0.0);
                pst2.setDouble(6, 0.0);
                pst2.setDouble(7, 0.0);
                pst2.setDouble(8, 0.0);
                pst2.setDouble(9, 0.0);
                pst2.setDouble(10, 0.0);
                pst2.setDouble(11, 0.0);
                pst2.setDouble(12, 0.0);
                pst2.setDouble(13, 0.0);
                pst2.setDouble(14, 0.0);
                pst2.setDouble(15, 0.0);
                pst2.setDouble(16, 0.0);
                pst2.setDouble(17, 0.0);
                pst2.setDouble(18, 0.0);
                pst2.setDouble(19, 0.0);
                pst2.setDouble(20, 0.0);
                pst2.setDouble(21, 0.0);
                pst2.setDouble(22, 0.0);
                pst2.setDouble(23, 0.0);
                pst2.setDouble(24, 0.0);
                pst2.setDouble(25, 0.0);
                pst2.setDouble(26, 0.0);
                pst2.setDouble(27, 0.0);
                pst2.setDouble(28, 0.0);
                pst2.setDouble(29, 0.0);
                pst2.setDouble(30, 0.0);
                pst2.setDouble(31, 0.0);
                pst2.setDouble(32, 0.0);
                pst2.setDouble(33, 0.0);
                pst2.setDouble(34, 0.0);
                pst2.setDouble(35, 0.0);
                pst2.setDouble(36, 0.0);
                pst2.setDouble(37, 0.0);
                pst2.setDouble(38, 0.0);
                pst2.setDouble(39, 0.0);
                pst2.setDouble(40, 0.0);
                pst2.setDouble(41, 0.0);
                pst2.setDouble(42, 0.0);
                pst2.setDouble(43, 0.0);
                pst2.setDouble(44, 0.0);
                pst2.setDouble(45, 0.0);
                pst2.setDouble(46, 0.0);
                pst2.setDouble(47, 0.0);
                pst2.setDouble(48, 0.0);
                pst2.setDouble(49, 0.0);
                pst2.executeUpdate();
                
            }
            else if("Business Studies".equals(st.getDept()))
            {
                pst3=(PreparedStatement) con.prepareStatement("INSERT INTO businessstudiessubjects(id, Name, Semester, Class, Bangla1st, B1CQ, B1MCQ, Bangla2nd, B2CQ, B2MCQ, English1st, English2nd, ICT, ICTCQ, ICTMCQ, Accounting1st, ACC1CQ, ACC1MCQ, Accounting2nd, ACC2CQ, ACC2MCQ, Economics1st, ECO1CQ, ECO1MCQ, Economics2nd, ECO2CQ, ECO2MCQ, FinanceBankingandInsurance1st, FBI1CQ, FBI1MCQ, FinanceBankingandInsurance2nd, FBI2CQ, FBI2MCQ, BusinessOrgandManagement1st, BOM1CQ, BOM1MCQ, BusinessOrgandManagement2nd, BOM2CQ, BOM2MCQ, TotalMarks) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                pst3.setInt(1, st.getID());
                pst3.setString(2, st.getName());
                pst3.setInt(3, st.getSemester());
                pst3.setInt(4, st.getclass());
                pst3.setDouble(5, 0.0);
                pst3.setDouble(6, 0.0);
                pst3.setDouble(7, 0.0);
                pst3.setDouble(8, 0.0);
                pst3.setDouble(9, 0.0);
                pst3.setDouble(10, 0.0);
                pst3.setDouble(11, 0.0);
                pst3.setDouble(12, 0.0);
                pst3.setDouble(13, 0.0);
                pst3.setDouble(14, 0.0);
                pst3.setDouble(15, 0.0);
                pst3.setDouble(16, 0.0);
                pst3.setDouble(17, 0.0);
                pst3.setDouble(18, 0.0);
                pst3.setDouble(19, 0.0);
                pst3.setDouble(20, 0.0);
                pst3.setDouble(21, 0.0);
                pst3.setDouble(22, 0.0);
                pst3.setDouble(23, 0.0);
                pst3.setDouble(24, 0.0);
                pst3.setDouble(25, 0.0);
                pst3.setDouble(26, 0.0);
                pst3.setDouble(27, 0.0);
                pst3.setDouble(28, 0.0);
                pst3.setDouble(29, 0.0);
                pst3.setDouble(30, 0.0);
                pst3.setDouble(31, 0.0);
                pst3.setDouble(32, 0.0);
                pst3.setDouble(33, 0.0);
                pst3.setDouble(34, 0.0);
                pst3.setDouble(35, 0.0);
                pst3.setDouble(36, 0.0);
                pst3.setDouble(37, 0.0);
                pst3.setDouble(38, 0.0);
                pst3.setDouble(39, 0.0);
                pst3.setDouble(40, 0.0);
                
                
                pst3.executeUpdate();
            }
            
            else if("Humanities".equals(st.getDept()))
            {
                pst4=(PreparedStatement) con.prepareStatement("INSERT INTO humanitiessubjects(id, Name, Semester, Class, Bangla1st, B1CQ, B1MCQ, Bangla2nd, B2CQ, B2MCQ, English1st, E1CQ, English2nd, E2CQ, ICT, ICTCQ, ICTMCQ, ICTLab, Sociology1st, SOC1CQ, SOC1MCQ, Sociology2nd, SOC2CQ, SOC2MCQ, Economics1st, ECO1CQ, ECO1MCQ, Economics2nd, ECO2CQ, ECO2MCQ, Geography1st, GEO1CQ, GEO1MCQ, Geography2nd, GEO2CQ, GEO2MCQ, Logic1st, LOG1CQ, LOG1MCQ, Logic2nd, LOG2CQ, LOG2MCQ, History1st, HIS1CQ, HIS1MCQ, History2nd, HIS2CQ, HIS2MCQ, SocialScience1st, Ss1CQ, Ss1MCQ, SocialScience2nd, Ss2CQ, Ss2MCQ, CivicandGoodGovernance1st, CGG1CQ, CGG1MCQ, CivicandGoodGovernance2nd, CGG2CQ, CGG2MCQ, IslamicHistoryandCulture1st, IHC1CQ, IHC1MCQ, IslamicHistoryandCulture2nd, IHC2CQ, IHC2MCQ, TotalMarks) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                
                pst4.setInt(1, st.getID());
                pst4.setString(2, st.getName());
                pst4.setInt(3, st.getSemester());
                pst4.setInt(4, st.getclass());
                pst4.setDouble(5, 0.0);
                pst4.setDouble(6, 0.0);
                pst4.setDouble(7, 0.0);
                pst4.setDouble(8, 0.0);
                pst4.setDouble(9, 0.0);
                pst4.setDouble(10, 0.0);
                pst4.setDouble(11, 0.0);
                pst4.setDouble(12, 0.0);
                pst4.setDouble(13, 0.0);
                pst4.setDouble(14, 0.0);
                pst4.setDouble(15, 0.0);
                pst4.setDouble(16, 0.0);
                pst4.setDouble(17, 0.0);
                pst4.setDouble(18, 0.0);
                pst4.setDouble(19, 0.0);
                pst4.setDouble(20, 0.0);
                pst4.setDouble(21, 0.0);
                pst4.setDouble(22, 0.0);
                pst4.setDouble(23, 0.0);
                pst4.setDouble(24, 0.0);
                pst4.setDouble(25, 0.0);
                pst4.setDouble(26, 0.0);
                pst4.setDouble(27, 0.0);
                pst4.setDouble(28, 0.0);
                pst4.setDouble(29, 0.0);
                pst4.setDouble(30, 0.0);
                pst4.setDouble(31, 0.0);
                pst4.setDouble(32, 0.0);
                pst4.setDouble(33, 0.0);
                pst4.setDouble(34, 0.0);
                pst4.setDouble(35, 0.0);
                pst4.setDouble(36, 0.0);
                pst4.setDouble(37, 0.0);
                pst4.setDouble(38, 0.0);
                pst4.setDouble(39, 0.0);
                pst4.setDouble(40, 0.0);
                pst4.setDouble(41, 0.0);
                pst4.setDouble(42, 0.0);
                pst4.setDouble(43, 0.0);
                pst4.setDouble(44, 0.0);
                pst4.setDouble(45, 0.0);
                pst4.setDouble(46, 0.0);
                pst4.setDouble(47, 0.0);
                pst4.setDouble(48, 0.0);
                pst4.setDouble(49, 0.0);
                pst4.setDouble(50, 0.0);
                pst4.setDouble(51, 0.0);
                pst4.setDouble(52, 0.0);
                pst4.setDouble(53, 0.0);
                pst4.setDouble(54, 0.0);
                pst4.setDouble(55, 0.0);
                pst4.setDouble(56, 0.0);
                pst4.setDouble(57, 0.0);
                pst4.setDouble(58, 0.0);
                pst4.setDouble(59, 0.0);
                pst4.setDouble(60, 0.0);
                pst4.setDouble(61, 0.0);
                pst4.setDouble(62, 0.0);
                pst4.setDouble(63, 0.0);
                pst4.setDouble(64, 0.0);
                pst4.setDouble(65, 0.0);
                pst4.setDouble(66, 0.0);
                pst4.setDouble(67, 0.0);
                
                pst4.executeUpdate();
            }
            
            pst.setInt(1, st.getID());
            pst.setString(2, st.getName());
            pst.setString(3, st.getFatherName());
            pst.setString(4, st.getMotherName());
            pst.setString(5, st.getDept());
            pst.setInt(6, age);
            pst.setString(7, st.getBirthDate());
            pst.setString(8, st.getbloodgroup());
            pst.setString(9, st.getgender());
            pst.setInt(10, st.getclass());
            pst.setInt(11, st.getSemester());
            pst.setString(12, st.getEmail());
            pst.setInt(13, st.getmobileNo());
            pst.setInt(14, st.getphone());
            pst.setString(15, st.getAddress());  
            pst.setString(16, st.getCGPA());
                
            pst.executeUpdate();
            pst5.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Information Updated!");
            this.setVisible(false);
            
            sl.setVisible(false);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EditInfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EditInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JTextField AgeField;
    private javax.swing.JTextField BDateField;
    private javax.swing.JTextField BloodGroupField;
    private javax.swing.JTextField CGPA;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField ContactField;
    private javax.swing.JTextField DeptField;
    private javax.swing.JTextField FathersNameField;
    private javax.swing.JTextField GNUM;
    private javax.swing.JTextField GenderField;
    private javax.swing.JTextField IDField;
    private javax.swing.JTextField MotherNameField;
    private javax.swing.JTextField NameField1;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField SemesterField;
    private javax.swing.JTextField YearField;
    private javax.swing.JTextField emailFeild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
